export const ASTRA_VIEWER_CLASS_NAME = 'astra-viewer' as const;

export const ASTRA_TOKEN_NAMES = [
  '--astra-paper',
  '--astra-surface',
  '--astra-surface-2',
  '--astra-ink',
  '--astra-ink-soft',
  '--astra-muted',
  '--astra-faint',
  '--astra-rule',
  '--astra-rule-strong',
  '--astra-accent',
  '--astra-link',
  '--astra-accent-soft',
  '--astra-kicker',
  '--astra-c-decision',
  '--astra-c-finding',
  '--astra-c-insight',
  '--astra-c-analysis',
  '--astra-c-output',
  '--astra-c-input',
  '--astra-c-value',
  '--astra-heading',
  '--astra-serif',
  '--astra-label',
  '--astra-mono',
  '--astra-color-surface',
  '--astra-color-surface-raised',
  '--astra-color-surface-muted',
  '--astra-color-text',
  '--astra-color-text-muted',
  '--astra-color-border',
  '--astra-color-accent',
  '--astra-color-accent-contrast',
  '--astra-color-danger',
  '--astra-color-warning',
  '--astra-color-success',
  '--astra-font-ui',
  '--astra-font-mono',
  '--astra-font-body',
  '--astra-font-heading',
  '--astra-font-size',
  '--astra-radius',
  '--astra-radius-sm',
  '--astra-radius-md',
  '--astra-shadow',
  '--astra-shadow-raised',
  '--astra-space-1',
  '--astra-space-2',
  '--astra-space-3',
  '--astra-space-4',
] as const;

export type AstraTokenName = (typeof ASTRA_TOKEN_NAMES)[number];
export type AstraThemeMode = 'host' | 'brand-light' | 'brand-dark';
